EJS:
  beautifiers:
    - Pretty Diff
    - JS-Beautify
  indent_size: 2
  indent_style: space
  max_preserve_newlines: 2
  quotes: double
  wrap_line_length: 83
  indent_comments: true
  end_with_newline: true
  preserve_newlines: false
  align_assignments: false
  break_chained_methods: true
  multiline_ternary: always-multiline
  space_after_anon_function: false
  comma_first: true
  indent_chained_methods: true
  jslint_happy: true
  keep_array_indentation: true
  space_before_conditional: true
  space_in_empty_paren: false
  space_in_paren: false
  unescape_strings: false
CSS:
  beautifiers:
    - Prettier
    - Pretty Diff
    - JS-Beautify
    - CSScomb
  indent_size: 2
  indent_style: space
  max_preserve_newlines: 2
  quotes: double
  wrap_line_length: 80
  end_with_newline: true
  pragma_insert: false
  pragma_require: false
  preserve_newlines: true
  newline_between_rules: true
  no_leading_zero: true
  selector_separator_newline: false
JSON:
  beautifiers:
    - Prettier
    - Pretty Diff
    - JS-Beautify
  indent_size: 2
  indent_style: space
  max_preserve_newlines: 0
  quotes: double
JSON5:
  beautifiers:
    - Prettier
    - Pretty Diff
    - JS-Beautify
  indent_style: space
  max_preserve_newlines: 0
  quotes: double
  indent_comments: true
HTML:
  beautifiers:
    - Pretty Diff
    - JS-Beautify
  indent_size: 2
  indent_style: space
  max_preserve_newlines: 2
  quotes: double
  wrap_line_length: 80
  indent_comments: true
  end_with_newline: true
  preserve_newlines: false
  brace_style: !<tag:yaml.org,2002:js/undefined> ''
  force_indentation: true
  indent_inner_html: true
  indent_scripts: normal
  newline_before_tags:
    - meta
    - link
    - title
  wrap_attributes: auto
  wrap_attributes_indent_size: 2
JavaScript:
  beautifiers:
    - Prettier
    - Pretty Diff
    - JS-Beautify
    - ESLint
  indent_size: 2
  indent_style: space
  max_preserve_newlines: 2
  quotes: double
  wrap_line_length: 80
  indent_comments: true
  end_with_newline: true
  pragma_insert: false
  pragma_require: false
  preserve_newlines: true
  align_assignments: false
  break_chained_methods: true
  end_with_comma: true
  multiline_ternary: always-multiline
  space_after_anon_function: false
  arrow_parens: as-needed
  comma_first: true
  end_with_semicolon: false
  indent_chained_methods: true
  jslint_happy: true
  jsx_brackets: !<tag:yaml.org,2002:js/undefined> ''
  keep_array_indentation: true
  object_curly_spacing: true
  space_before_conditional: true
  space_in_empty_paren: false
  space_in_paren: false
  unescape_strings: false
  remove_trailing_whitespace: true
Markdown:
  beautifiers:
    - Prettier
  wrap_line_length: 80
  pragma_insert: false
  pragma_require: false
  wrap_prose: always
SVG:
  beautifiers:
    - Pretty Diff
  indent_size: 2
  indent_style: space
  max_preserve_newlines: 2
  quotes: double
  wrap_line_length: 80
  indent_comments: true
  force_indentation: true
TypeScript:
  beautifiers:
    - Prettier
    - Pretty Diff
    - TSLint
  indent_size: 2
  indent_style: space
  max_preserve_newlines: 2
  quotes: double
  wrap_line_length: 80
  indent_comments: true
  pragma_insert: false
  pragma_require: false
  align_assignments: false
  break_chained_methods: true
  end_with_comma: true
  multiline_ternary: always-multiline
  space_after_anon_function: false
  arrow_parens: as-needed
  end_with_semicolon: false
  jsx_brackets: !<tag:yaml.org,2002:js/undefined> ''
  object_curly_spacing: true
